/* 
 * OANDA v20 API
 *
 * The full OANDA v20 API Specification. This specification defines how to interact with v20 Accounts, Trades, Orders, Pricing and more.
 *
 * The version of the OpenAPI document: 3.0.25
 * Contact: api@oanda.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = GeriRemenyi.Oanda.V20.Client.OpenAPIDateConverter;

namespace GeriRemenyi.Oanda.V20.Model
{
    /// <summary>
    /// The reason that the Market Order was created
    /// </summary>
    /// <value>The reason that the Market Order was created</value>
    
    [JsonConverter(typeof(StringEnumConverter))]
    
    public enum MarketOrderReason
    {
        /// <summary>
        /// Enum CLIENTORDER for value: CLIENT_ORDER
        /// </summary>
        [EnumMember(Value = "CLIENT_ORDER")]
        CLIENTORDER = 1,

        /// <summary>
        /// Enum TRADECLOSE for value: TRADE_CLOSE
        /// </summary>
        [EnumMember(Value = "TRADE_CLOSE")]
        TRADECLOSE = 2,

        /// <summary>
        /// Enum POSITIONCLOSEOUT for value: POSITION_CLOSEOUT
        /// </summary>
        [EnumMember(Value = "POSITION_CLOSEOUT")]
        POSITIONCLOSEOUT = 3,

        /// <summary>
        /// Enum MARGINCLOSEOUT for value: MARGIN_CLOSEOUT
        /// </summary>
        [EnumMember(Value = "MARGIN_CLOSEOUT")]
        MARGINCLOSEOUT = 4,

        /// <summary>
        /// Enum DELAYEDTRADECLOSE for value: DELAYED_TRADE_CLOSE
        /// </summary>
        [EnumMember(Value = "DELAYED_TRADE_CLOSE")]
        DELAYEDTRADECLOSE = 5

    }

}
