/* 
 * OANDA v20 API
 *
 * The full OANDA v20 API Specification. This specification defines how to interact with v20 Accounts, Trades, Orders, Pricing and more.
 *
 * The version of the OpenAPI document: 3.0.25
 * Contact: api@oanda.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = GeriRemenyi.Oanda.V20.Client.OpenAPIDateConverter;

namespace GeriRemenyi.Oanda.V20.Model
{
    /// <summary>
    /// The time in force for the created Stop Loss Order. This may only be GTC, GTD or GFD.
    /// </summary>
    /// <value>The time in force for the created Stop Loss Order. This may only be GTC, GTD or GFD.</value>
    
    [JsonConverter(typeof(StringEnumConverter))]
    
    public enum TradeOrderTimeInForce
    {
        /// <summary>
        /// Enum GTC for value: GTC
        /// </summary>
        [EnumMember(Value = "GTC")]
        GTC = 1,

        /// <summary>
        /// Enum GTD for value: GTD
        /// </summary>
        [EnumMember(Value = "GTD")]
        GTD = 2,

        /// <summary>
        /// Enum GFD for value: GFD
        /// </summary>
        [EnumMember(Value = "GFD")]
        GFD = 3

    }

}
