/* 
 * OANDA v20 API
 *
 * The full OANDA v20 API Specification. This specification defines how to interact with v20 Accounts, Trades, Orders, Pricing and more.
 *
 * The version of the OpenAPI document: 3.0.25
 * Contact: api@oanda.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using GeriRemenyi.Oanda.V20.Api;
using GeriRemenyi.Oanda.V20.Model;
using GeriRemenyi.Oanda.V20.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace GeriRemenyi.Oanda.V20.Test
{
    /// <summary>
    ///  Class for testing Candlestick
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CandlestickTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Candlestick
        //private Candlestick instance;

        public CandlestickTests()
        {
            // TODO uncomment below to create an instance of Candlestick
            //instance = new Candlestick();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Candlestick
        /// </summary>
        [Fact]
        public void CandlestickInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Candlestick
            //Assert.IsInstanceOfType<Candlestick> (instance, "variable 'instance' is a Candlestick");
        }


        /// <summary>
        /// Test the property 'Time'
        /// </summary>
        [Fact]
        public void TimeTest()
        {
            // TODO unit test for the property 'Time'
        }
        /// <summary>
        /// Test the property 'Bid'
        /// </summary>
        [Fact]
        public void BidTest()
        {
            // TODO unit test for the property 'Bid'
        }
        /// <summary>
        /// Test the property 'Ask'
        /// </summary>
        [Fact]
        public void AskTest()
        {
            // TODO unit test for the property 'Ask'
        }
        /// <summary>
        /// Test the property 'Mid'
        /// </summary>
        [Fact]
        public void MidTest()
        {
            // TODO unit test for the property 'Mid'
        }
        /// <summary>
        /// Test the property 'Volume'
        /// </summary>
        [Fact]
        public void VolumeTest()
        {
            // TODO unit test for the property 'Volume'
        }
        /// <summary>
        /// Test the property 'Complete'
        /// </summary>
        [Fact]
        public void CompleteTest()
        {
            // TODO unit test for the property 'Complete'
        }

    }

}
