/* 
 * OANDA v20 API
 *
 * The full OANDA v20 API Specification. This specification defines how to interact with v20 Accounts, Trades, Orders, Pricing and more.
 *
 * The version of the OpenAPI document: 3.0.25
 * Contact: api@oanda.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using GeriRemenyi.Oanda.V20.Api;
using GeriRemenyi.Oanda.V20.Model;
using GeriRemenyi.Oanda.V20.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace GeriRemenyi.Oanda.V20.Test
{
    /// <summary>
    ///  Class for testing InlineResponse2007OrderBook
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class InlineResponse2007OrderBookTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for InlineResponse2007OrderBook
        //private InlineResponse2007OrderBook instance;

        public InlineResponse2007OrderBookTests()
        {
            // TODO uncomment below to create an instance of InlineResponse2007OrderBook
            //instance = new InlineResponse2007OrderBook();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of InlineResponse2007OrderBook
        /// </summary>
        [Fact]
        public void InlineResponse2007OrderBookInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" InlineResponse2007OrderBook
            //Assert.IsInstanceOfType<InlineResponse2007OrderBook> (instance, "variable 'instance' is a InlineResponse2007OrderBook");
        }


        /// <summary>
        /// Test the property 'Instrument'
        /// </summary>
        [Fact]
        public void InstrumentTest()
        {
            // TODO unit test for the property 'Instrument'
        }
        /// <summary>
        /// Test the property 'Time'
        /// </summary>
        [Fact]
        public void TimeTest()
        {
            // TODO unit test for the property 'Time'
        }
        /// <summary>
        /// Test the property 'Price'
        /// </summary>
        [Fact]
        public void PriceTest()
        {
            // TODO unit test for the property 'Price'
        }
        /// <summary>
        /// Test the property 'BucketWidth'
        /// </summary>
        [Fact]
        public void BucketWidthTest()
        {
            // TODO unit test for the property 'BucketWidth'
        }
        /// <summary>
        /// Test the property 'Buckets'
        /// </summary>
        [Fact]
        public void BucketsTest()
        {
            // TODO unit test for the property 'Buckets'
        }

    }

}
