/* 
 * OANDA v20 API
 *
 * The full OANDA v20 API Specification. This specification defines how to interact with v20 Accounts, Trades, Orders, Pricing and more.
 *
 * The version of the OpenAPI document: 3.0.25
 * Contact: api@oanda.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using GeriRemenyi.Oanda.V20.Api;
using GeriRemenyi.Oanda.V20.Model;
using GeriRemenyi.Oanda.V20.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace GeriRemenyi.Oanda.V20.Test
{
    /// <summary>
    ///  Class for testing InlineResponse2002
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class InlineResponse2002Tests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for InlineResponse2002
        //private InlineResponse2002 instance;

        public InlineResponse2002Tests()
        {
            // TODO uncomment below to create an instance of InlineResponse2002
            //instance = new InlineResponse2002();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of InlineResponse2002
        /// </summary>
        [Fact]
        public void InlineResponse2002InstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" InlineResponse2002
            //Assert.IsInstanceOfType<InlineResponse2002> (instance, "variable 'instance' is a InlineResponse2002");
        }


        /// <summary>
        /// Test the property 'Account'
        /// </summary>
        [Fact]
        public void AccountTest()
        {
            // TODO unit test for the property 'Account'
        }
        /// <summary>
        /// Test the property 'LastTransactionID'
        /// </summary>
        [Fact]
        public void LastTransactionIDTest()
        {
            // TODO unit test for the property 'LastTransactionID'
        }

    }

}
