/* 
 * OANDA v20 API
 *
 * The full OANDA v20 API Specification. This specification defines how to interact with v20 Accounts, Trades, Orders, Pricing and more.
 *
 * The version of the OpenAPI document: 3.0.25
 * Contact: api@oanda.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using GeriRemenyi.Oanda.V20.Api;
using GeriRemenyi.Oanda.V20.Model;
using GeriRemenyi.Oanda.V20.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace GeriRemenyi.Oanda.V20.Test
{
    /// <summary>
    ///  Class for testing InlineResponse2005ChangesOrdersCreated
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class InlineResponse2005ChangesOrdersCreatedTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for InlineResponse2005ChangesOrdersCreated
        //private InlineResponse2005ChangesOrdersCreated instance;

        public InlineResponse2005ChangesOrdersCreatedTests()
        {
            // TODO uncomment below to create an instance of InlineResponse2005ChangesOrdersCreated
            //instance = new InlineResponse2005ChangesOrdersCreated();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of InlineResponse2005ChangesOrdersCreated
        /// </summary>
        [Fact]
        public void InlineResponse2005ChangesOrdersCreatedInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" InlineResponse2005ChangesOrdersCreated
            //Assert.IsInstanceOfType<InlineResponse2005ChangesOrdersCreated> (instance, "variable 'instance' is a InlineResponse2005ChangesOrdersCreated");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'CreateTime'
        /// </summary>
        [Fact]
        public void CreateTimeTest()
        {
            // TODO unit test for the property 'CreateTime'
        }
        /// <summary>
        /// Test the property 'State'
        /// </summary>
        [Fact]
        public void StateTest()
        {
            // TODO unit test for the property 'State'
        }
        /// <summary>
        /// Test the property 'ClientExtensions'
        /// </summary>
        [Fact]
        public void ClientExtensionsTest()
        {
            // TODO unit test for the property 'ClientExtensions'
        }

    }

}
