/* 
 * OANDA v20 API
 *
 * The full OANDA v20 API Specification. This specification defines how to interact with v20 Accounts, Trades, Orders, Pricing and more.
 *
 * The version of the OpenAPI document: 3.0.25
 * Contact: api@oanda.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using GeriRemenyi.Oanda.V20.Api;
using GeriRemenyi.Oanda.V20.Model;
using GeriRemenyi.Oanda.V20.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace GeriRemenyi.Oanda.V20.Test
{
    /// <summary>
    ///  Class for testing OrderFillTransactionTradeOpened
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OrderFillTransactionTradeOpenedTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for OrderFillTransactionTradeOpened
        //private OrderFillTransactionTradeOpened instance;

        public OrderFillTransactionTradeOpenedTests()
        {
            // TODO uncomment below to create an instance of OrderFillTransactionTradeOpened
            //instance = new OrderFillTransactionTradeOpened();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OrderFillTransactionTradeOpened
        /// </summary>
        [Fact]
        public void OrderFillTransactionTradeOpenedInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" OrderFillTransactionTradeOpened
            //Assert.IsInstanceOfType<OrderFillTransactionTradeOpened> (instance, "variable 'instance' is a OrderFillTransactionTradeOpened");
        }


        /// <summary>
        /// Test the property 'TradeID'
        /// </summary>
        [Fact]
        public void TradeIDTest()
        {
            // TODO unit test for the property 'TradeID'
        }
        /// <summary>
        /// Test the property 'Units'
        /// </summary>
        [Fact]
        public void UnitsTest()
        {
            // TODO unit test for the property 'Units'
        }
        /// <summary>
        /// Test the property 'Price'
        /// </summary>
        [Fact]
        public void PriceTest()
        {
            // TODO unit test for the property 'Price'
        }
        /// <summary>
        /// Test the property 'GuaranteedExecutionFee'
        /// </summary>
        [Fact]
        public void GuaranteedExecutionFeeTest()
        {
            // TODO unit test for the property 'GuaranteedExecutionFee'
        }
        /// <summary>
        /// Test the property 'ClientExtensions'
        /// </summary>
        [Fact]
        public void ClientExtensionsTest()
        {
            // TODO unit test for the property 'ClientExtensions'
        }
        /// <summary>
        /// Test the property 'HalfSpreadCost'
        /// </summary>
        [Fact]
        public void HalfSpreadCostTest()
        {
            // TODO unit test for the property 'HalfSpreadCost'
        }
        /// <summary>
        /// Test the property 'InitialMarginRequired'
        /// </summary>
        [Fact]
        public void InitialMarginRequiredTest()
        {
            // TODO unit test for the property 'InitialMarginRequired'
        }

    }

}
