/* 
 * OANDA v20 API
 *
 * The full OANDA v20 API Specification. This specification defines how to interact with v20 Accounts, Trades, Orders, Pricing and more.
 *
 * The version of the OpenAPI document: 3.0.25
 * Contact: api@oanda.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using GeriRemenyi.Oanda.V20.Api;
using GeriRemenyi.Oanda.V20.Model;
using GeriRemenyi.Oanda.V20.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace GeriRemenyi.Oanda.V20.Test
{
    /// <summary>
    ///  Class for testing StopLossOrderAllOf
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class StopLossOrderAllOfTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for StopLossOrderAllOf
        //private StopLossOrderAllOf instance;

        public StopLossOrderAllOfTests()
        {
            // TODO uncomment below to create an instance of StopLossOrderAllOf
            //instance = new StopLossOrderAllOf();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of StopLossOrderAllOf
        /// </summary>
        [Fact]
        public void StopLossOrderAllOfInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" StopLossOrderAllOf
            //Assert.IsInstanceOfType<StopLossOrderAllOf> (instance, "variable 'instance' is a StopLossOrderAllOf");
        }


        /// <summary>
        /// Test the property 'Price'
        /// </summary>
        [Fact]
        public void PriceTest()
        {
            // TODO unit test for the property 'Price'
        }
        /// <summary>
        /// Test the property 'GuaranteedExecutionPremium'
        /// </summary>
        [Fact]
        public void GuaranteedExecutionPremiumTest()
        {
            // TODO unit test for the property 'GuaranteedExecutionPremium'
        }
        /// <summary>
        /// Test the property 'Distance'
        /// </summary>
        [Fact]
        public void DistanceTest()
        {
            // TODO unit test for the property 'Distance'
        }
        /// <summary>
        /// Test the property 'Guaranteed'
        /// </summary>
        [Fact]
        public void GuaranteedTest()
        {
            // TODO unit test for the property 'Guaranteed'
        }

    }

}
