/* 
 * OANDA v20 API
 *
 * The full OANDA v20 API Specification. This specification defines how to interact with v20 Accounts, Trades, Orders, Pricing and more.
 *
 * The version of the OpenAPI document: 3.0.25
 * Contact: api@oanda.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using GeriRemenyi.Oanda.V20.Api;
using GeriRemenyi.Oanda.V20.Model;
using GeriRemenyi.Oanda.V20.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace GeriRemenyi.Oanda.V20.Test
{
    /// <summary>
    ///  Class for testing TakeProfitOrderAllOf
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TakeProfitOrderAllOfTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TakeProfitOrderAllOf
        //private TakeProfitOrderAllOf instance;

        public TakeProfitOrderAllOfTests()
        {
            // TODO uncomment below to create an instance of TakeProfitOrderAllOf
            //instance = new TakeProfitOrderAllOf();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TakeProfitOrderAllOf
        /// </summary>
        [Fact]
        public void TakeProfitOrderAllOfInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" TakeProfitOrderAllOf
            //Assert.IsInstanceOfType<TakeProfitOrderAllOf> (instance, "variable 'instance' is a TakeProfitOrderAllOf");
        }


        /// <summary>
        /// Test the property 'Price'
        /// </summary>
        [Fact]
        public void PriceTest()
        {
            // TODO unit test for the property 'Price'
        }

    }

}
