/* 
 * OANDA v20 API
 *
 * The full OANDA v20 API Specification. This specification defines how to interact with v20 Accounts, Trades, Orders, Pricing and more.
 *
 * The version of the OpenAPI document: 3.0.25
 * Contact: api@oanda.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using GeriRemenyi.Oanda.V20.Api;
using GeriRemenyi.Oanda.V20.Model;
using GeriRemenyi.Oanda.V20.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace GeriRemenyi.Oanda.V20.Test
{
    /// <summary>
    ///  Class for testing TradeOrderTriggerCondition
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TradeOrderTriggerConditionTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TradeOrderTriggerCondition
        //private TradeOrderTriggerCondition instance;

        public TradeOrderTriggerConditionTests()
        {
            // TODO uncomment below to create an instance of TradeOrderTriggerCondition
            //instance = new TradeOrderTriggerCondition();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TradeOrderTriggerCondition
        /// </summary>
        [Fact]
        public void TradeOrderTriggerConditionInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" TradeOrderTriggerCondition
            //Assert.IsInstanceOfType<TradeOrderTriggerCondition> (instance, "variable 'instance' is a TradeOrderTriggerCondition");
        }



    }

}
