/* 
 * OANDA v20 API
 *
 * The full OANDA v20 API Specification. This specification defines how to interact with v20 Accounts, Trades, Orders, Pricing and more.
 *
 * The version of the OpenAPI document: 3.0.25
 * Contact: api@oanda.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using GeriRemenyi.Oanda.V20.Client.Api;
using GeriRemenyi.Oanda.V20.Client.Model;
using GeriRemenyi.Oanda.V20.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace GeriRemenyi.Oanda.V20.Client.Test
{
    /// <summary>
    ///  Class for testing AccountChangesResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AccountChangesResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AccountChangesResponse
        //private AccountChangesResponse instance;

        public AccountChangesResponseTests()
        {
            // TODO uncomment below to create an instance of AccountChangesResponse
            //instance = new AccountChangesResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AccountChangesResponse
        /// </summary>
        [Fact]
        public void AccountChangesResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" AccountChangesResponse
            //Assert.IsInstanceOfType<AccountChangesResponse> (instance, "variable 'instance' is a AccountChangesResponse");
        }


        /// <summary>
        /// Test the property 'Changes'
        /// </summary>
        [Fact]
        public void ChangesTest()
        {
            // TODO unit test for the property 'Changes'
        }
        /// <summary>
        /// Test the property 'State'
        /// </summary>
        [Fact]
        public void StateTest()
        {
            // TODO unit test for the property 'State'
        }
        /// <summary>
        /// Test the property 'LastTransactionID'
        /// </summary>
        [Fact]
        public void LastTransactionIDTest()
        {
            // TODO unit test for the property 'LastTransactionID'
        }

    }

}
