/* 
 * OANDA v20 API
 *
 * The full OANDA v20 API Specification. This specification defines how to interact with v20 Accounts, Trades, Orders, Pricing and more.
 *
 * The version of the OpenAPI document: 3.0.25
 * Contact: api@oanda.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using GeriRemenyi.Oanda.V20.Client.Api;
using GeriRemenyi.Oanda.V20.Client.Model;
using GeriRemenyi.Oanda.V20.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace GeriRemenyi.Oanda.V20.Client.Test
{
    /// <summary>
    ///  Class for testing CloseTradeResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CloseTradeResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CloseTradeResponse
        //private CloseTradeResponse instance;

        public CloseTradeResponseTests()
        {
            // TODO uncomment below to create an instance of CloseTradeResponse
            //instance = new CloseTradeResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CloseTradeResponse
        /// </summary>
        [Fact]
        public void CloseTradeResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CloseTradeResponse
            //Assert.IsInstanceOfType<CloseTradeResponse> (instance, "variable 'instance' is a CloseTradeResponse");
        }


        /// <summary>
        /// Test the property 'OrderCreateTransaction'
        /// </summary>
        [Fact]
        public void OrderCreateTransactionTest()
        {
            // TODO unit test for the property 'OrderCreateTransaction'
        }
        /// <summary>
        /// Test the property 'OrderFillTransaction'
        /// </summary>
        [Fact]
        public void OrderFillTransactionTest()
        {
            // TODO unit test for the property 'OrderFillTransaction'
        }
        /// <summary>
        /// Test the property 'OrderCancelTransaction'
        /// </summary>
        [Fact]
        public void OrderCancelTransactionTest()
        {
            // TODO unit test for the property 'OrderCancelTransaction'
        }
        /// <summary>
        /// Test the property 'LastTransactionID'
        /// </summary>
        [Fact]
        public void LastTransactionIDTest()
        {
            // TODO unit test for the property 'LastTransactionID'
        }
        /// <summary>
        /// Test the property 'RelatedTransactionIDs'
        /// </summary>
        [Fact]
        public void RelatedTransactionIDsTest()
        {
            // TODO unit test for the property 'RelatedTransactionIDs'
        }

    }

}
