/* 
 * OANDA v20 API
 *
 * The full OANDA v20 API Specification. This specification defines how to interact with v20 Accounts, Trades, Orders, Pricing and more.
 *
 * The version of the OpenAPI document: 3.0.25
 * Contact: api@oanda.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using GeriRemenyi.Oanda.V20.Client.Api;
using GeriRemenyi.Oanda.V20.Client.Model;
using GeriRemenyi.Oanda.V20.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace GeriRemenyi.Oanda.V20.Client.Test
{
    /// <summary>
    ///  Class for testing CreateOrderBadRequestResponseAllOf
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CreateOrderBadRequestResponseAllOfTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CreateOrderBadRequestResponseAllOf
        //private CreateOrderBadRequestResponseAllOf instance;

        public CreateOrderBadRequestResponseAllOfTests()
        {
            // TODO uncomment below to create an instance of CreateOrderBadRequestResponseAllOf
            //instance = new CreateOrderBadRequestResponseAllOf();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CreateOrderBadRequestResponseAllOf
        /// </summary>
        [Fact]
        public void CreateOrderBadRequestResponseAllOfInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CreateOrderBadRequestResponseAllOf
            //Assert.IsInstanceOfType<CreateOrderBadRequestResponseAllOf> (instance, "variable 'instance' is a CreateOrderBadRequestResponseAllOf");
        }


        /// <summary>
        /// Test the property 'OrderRejectTransaction'
        /// </summary>
        [Fact]
        public void OrderRejectTransactionTest()
        {
            // TODO unit test for the property 'OrderRejectTransaction'
        }

    }

}
