/* 
 * OANDA v20 API
 *
 * The full OANDA v20 API Specification. This specification defines how to interact with v20 Accounts, Trades, Orders, Pricing and more.
 *
 * The version of the OpenAPI document: 3.0.25
 * Contact: api@oanda.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using GeriRemenyi.Oanda.V20.Client.Api;
using GeriRemenyi.Oanda.V20.Client.Model;
using GeriRemenyi.Oanda.V20.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace GeriRemenyi.Oanda.V20.Client.Test
{
    /// <summary>
    ///  Class for testing Error401
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class Error401Tests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Error401
        //private Error401 instance;

        public Error401Tests()
        {
            // TODO uncomment below to create an instance of Error401
            //instance = new Error401();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Error401
        /// </summary>
        [Fact]
        public void Error401InstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Error401
            //Assert.IsInstanceOfType<Error401> (instance, "variable 'instance' is a Error401");
        }



    }

}
