/* 
 * OANDA v20 API
 *
 * The full OANDA v20 API Specification. This specification defines how to interact with v20 Accounts, Trades, Orders, Pricing and more.
 *
 * The version of the OpenAPI document: 3.0.25
 * Contact: api@oanda.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using GeriRemenyi.Oanda.V20.Client.Api;
using GeriRemenyi.Oanda.V20.Client.Model;
using GeriRemenyi.Oanda.V20.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace GeriRemenyi.Oanda.V20.Client.Test
{
    /// <summary>
    ///  Class for testing OrderClientExtensionsModifyRejectTransaction
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OrderClientExtensionsModifyRejectTransactionTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for OrderClientExtensionsModifyRejectTransaction
        //private OrderClientExtensionsModifyRejectTransaction instance;

        public OrderClientExtensionsModifyRejectTransactionTests()
        {
            // TODO uncomment below to create an instance of OrderClientExtensionsModifyRejectTransaction
            //instance = new OrderClientExtensionsModifyRejectTransaction();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OrderClientExtensionsModifyRejectTransaction
        /// </summary>
        [Fact]
        public void OrderClientExtensionsModifyRejectTransactionInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" OrderClientExtensionsModifyRejectTransaction
            //Assert.IsInstanceOfType<OrderClientExtensionsModifyRejectTransaction> (instance, "variable 'instance' is a OrderClientExtensionsModifyRejectTransaction");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Time'
        /// </summary>
        [Fact]
        public void TimeTest()
        {
            // TODO unit test for the property 'Time'
        }
        /// <summary>
        /// Test the property 'UserID'
        /// </summary>
        [Fact]
        public void UserIDTest()
        {
            // TODO unit test for the property 'UserID'
        }
        /// <summary>
        /// Test the property 'AccountID'
        /// </summary>
        [Fact]
        public void AccountIDTest()
        {
            // TODO unit test for the property 'AccountID'
        }
        /// <summary>
        /// Test the property 'BatchID'
        /// </summary>
        [Fact]
        public void BatchIDTest()
        {
            // TODO unit test for the property 'BatchID'
        }
        /// <summary>
        /// Test the property 'RequestID'
        /// </summary>
        [Fact]
        public void RequestIDTest()
        {
            // TODO unit test for the property 'RequestID'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'RejectReason'
        /// </summary>
        [Fact]
        public void RejectReasonTest()
        {
            // TODO unit test for the property 'RejectReason'
        }
        /// <summary>
        /// Test the property 'OrderID'
        /// </summary>
        [Fact]
        public void OrderIDTest()
        {
            // TODO unit test for the property 'OrderID'
        }
        /// <summary>
        /// Test the property 'ClientOrderID'
        /// </summary>
        [Fact]
        public void ClientOrderIDTest()
        {
            // TODO unit test for the property 'ClientOrderID'
        }
        /// <summary>
        /// Test the property 'ClientExtensionsModify'
        /// </summary>
        [Fact]
        public void ClientExtensionsModifyTest()
        {
            // TODO unit test for the property 'ClientExtensionsModify'
        }
        /// <summary>
        /// Test the property 'TradeClientExtensionsModify'
        /// </summary>
        [Fact]
        public void TradeClientExtensionsModifyTest()
        {
            // TODO unit test for the property 'TradeClientExtensionsModify'
        }

    }

}
