/* 
 * OANDA v20 API
 *
 * The full OANDA v20 API Specification. This specification defines how to interact with v20 Accounts, Trades, Orders, Pricing and more.
 *
 * The version of the OpenAPI document: 3.0.25
 * Contact: api@oanda.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = GeriRemenyi.Oanda.V20.Client.Client.OpenAPIDateConverter;

namespace GeriRemenyi.Oanda.V20.Client.Model
{
    /// <summary>
    /// AccountSummaryAllOf
    /// </summary>
    [DataContract]
    public partial class AccountSummaryAllOf :  IEquatable<AccountSummaryAllOf>, IValidatableObject
    {
        /// <summary>
        /// Gets or Sets Currency
        /// </summary>
        [DataMember(Name="currency", EmitDefaultValue=false)]
        public AccountCurrency? Currency { get; set; }
        /// <summary>
        /// Gets or Sets GuaranteedStopLossOrderMode
        /// </summary>
        [DataMember(Name="guaranteedStopLossOrderMode", EmitDefaultValue=false)]
        public AccountGuaranteedStopLossOrderMode? GuaranteedStopLossOrderMode { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="AccountSummaryAllOf" /> class.
        /// </summary>
        /// <param name="id">The Account&#39;s identifier.</param>
        /// <param name="alias">Client-assigned alias for the Account. Only provided if the Account has an alias set.</param>
        /// <param name="currency">currency.</param>
        /// <param name="balance">The current balance of the Account..</param>
        /// <param name="createdByUserID">ID of the user that created the Account..</param>
        /// <param name="createdTime">A date and time value using either RFC3339 or UNIX time representation. The RFC 3339 representation is a string conforming to https://tools.ietf.org/rfc/rfc3339.txt. The Unix representation is a string representing the number of seconds since the Unix Epoch (January 1st, 1970 at UTC). The value is a fractional number, where the fractional part represents a fraction of a second (up to nine decimal places)..</param>
        /// <param name="guaranteedStopLossOrderMode">guaranteedStopLossOrderMode.</param>
        /// <param name="pl">The total profit/loss realized over the lifetime of the Account..</param>
        /// <param name="resettablePL">The total realized profit/loss for the Account since it was last reset by the client..</param>
        /// <param name="resettablePLTime">A date and time value using either RFC3339 or UNIX time representation. The RFC 3339 representation is a string conforming to https://tools.ietf.org/rfc/rfc3339.txt. The Unix representation is a string representing the number of seconds since the Unix Epoch (January 1st, 1970 at UTC). The value is a fractional number, where the fractional part represents a fraction of a second (up to nine decimal places)..</param>
        /// <param name="financing">The total amount of financing paid/collected over the lifetime of the Account..</param>
        /// <param name="commission">The total amount of commission paid over the lifetime of the Account..</param>
        /// <param name="guaranteedExecutionFees">The total amount of fees charged over the lifetime of the Account for the execution of guaranteed Stop Loss Orders..</param>
        /// <param name="marginRate">Client-provided margin rate override for the Account. The effective margin rate of the Account is the lesser of this value and the OANDA margin rate for the Account&#39;s division. This value is only provided if a margin rate override exists for the Account..</param>
        /// <param name="marginCallEnterTime">A date and time value using either RFC3339 or UNIX time representation. The RFC 3339 representation is a string conforming to https://tools.ietf.org/rfc/rfc3339.txt. The Unix representation is a string representing the number of seconds since the Unix Epoch (January 1st, 1970 at UTC). The value is a fractional number, where the fractional part represents a fraction of a second (up to nine decimal places)..</param>
        /// <param name="marginCallExtensionCount">The number of times that the Account&#39;s current margin call was extended..</param>
        /// <param name="lastMarginCallExtensionTime">A date and time value using either RFC3339 or UNIX time representation. The RFC 3339 representation is a string conforming to https://tools.ietf.org/rfc/rfc3339.txt. The Unix representation is a string representing the number of seconds since the Unix Epoch (January 1st, 1970 at UTC). The value is a fractional number, where the fractional part represents a fraction of a second (up to nine decimal places)..</param>
        /// <param name="openTradeCount">The number of Trades currently open in the Account..</param>
        /// <param name="openPositionCount">The number of Positions currently open in the Account..</param>
        /// <param name="pendingOrderCount">The number of Orders currently pending in the Account..</param>
        /// <param name="hedgingEnabled">Flag indicating that the Account has hedging enabled..</param>
        /// <param name="lastOrderFillTimestamp">A date and time value using either RFC3339 or UNIX time representation. The RFC 3339 representation is a string conforming to https://tools.ietf.org/rfc/rfc3339.txt. The Unix representation is a string representing the number of seconds since the Unix Epoch (January 1st, 1970 at UTC). The value is a fractional number, where the fractional part represents a fraction of a second (up to nine decimal places)..</param>
        /// <param name="lastTransactionId">The ID of the last Transaction created for the Account..</param>
        public AccountSummaryAllOf(string id = default(string), string alias = default(string), AccountCurrency? currency = default(AccountCurrency?), double balance = default(double), int createdByUserID = default(int), string createdTime = default(string), AccountGuaranteedStopLossOrderMode? guaranteedStopLossOrderMode = default(AccountGuaranteedStopLossOrderMode?), double pl = default(double), double resettablePL = default(double), string resettablePLTime = default(string), double financing = default(double), double commission = default(double), double guaranteedExecutionFees = default(double), double marginRate = default(double), string marginCallEnterTime = default(string), int marginCallExtensionCount = default(int), string lastMarginCallExtensionTime = default(string), int openTradeCount = default(int), int openPositionCount = default(int), int pendingOrderCount = default(int), bool hedgingEnabled = default(bool), string lastOrderFillTimestamp = default(string), int lastTransactionId = default(int))
        {
            this.Id = id;
            this.Alias = alias;
            this.Currency = currency;
            this.Balance = balance;
            this.CreatedByUserID = createdByUserID;
            this.CreatedTime = createdTime;
            this.GuaranteedStopLossOrderMode = guaranteedStopLossOrderMode;
            this.Pl = pl;
            this.ResettablePL = resettablePL;
            this.ResettablePLTime = resettablePLTime;
            this.Financing = financing;
            this.Commission = commission;
            this.GuaranteedExecutionFees = guaranteedExecutionFees;
            this.MarginRate = marginRate;
            this.MarginCallEnterTime = marginCallEnterTime;
            this.MarginCallExtensionCount = marginCallExtensionCount;
            this.LastMarginCallExtensionTime = lastMarginCallExtensionTime;
            this.OpenTradeCount = openTradeCount;
            this.OpenPositionCount = openPositionCount;
            this.PendingOrderCount = pendingOrderCount;
            this.HedgingEnabled = hedgingEnabled;
            this.LastOrderFillTimestamp = lastOrderFillTimestamp;
            this.LastTransactionId = lastTransactionId;
        }
        
        /// <summary>
        /// The Account&#39;s identifier
        /// </summary>
        /// <value>The Account&#39;s identifier</value>
        [DataMember(Name="id", EmitDefaultValue=false)]
        public string Id { get; set; }

        /// <summary>
        /// Client-assigned alias for the Account. Only provided if the Account has an alias set
        /// </summary>
        /// <value>Client-assigned alias for the Account. Only provided if the Account has an alias set</value>
        [DataMember(Name="alias", EmitDefaultValue=true)]
        public string Alias { get; set; }

        /// <summary>
        /// The current balance of the Account.
        /// </summary>
        /// <value>The current balance of the Account.</value>
        [DataMember(Name="balance", EmitDefaultValue=false)]
        public double Balance { get; set; }

        /// <summary>
        /// ID of the user that created the Account.
        /// </summary>
        /// <value>ID of the user that created the Account.</value>
        [DataMember(Name="createdByUserID", EmitDefaultValue=false)]
        public int CreatedByUserID { get; set; }

        /// <summary>
        /// A date and time value using either RFC3339 or UNIX time representation. The RFC 3339 representation is a string conforming to https://tools.ietf.org/rfc/rfc3339.txt. The Unix representation is a string representing the number of seconds since the Unix Epoch (January 1st, 1970 at UTC). The value is a fractional number, where the fractional part represents a fraction of a second (up to nine decimal places).
        /// </summary>
        /// <value>A date and time value using either RFC3339 or UNIX time representation. The RFC 3339 representation is a string conforming to https://tools.ietf.org/rfc/rfc3339.txt. The Unix representation is a string representing the number of seconds since the Unix Epoch (January 1st, 1970 at UTC). The value is a fractional number, where the fractional part represents a fraction of a second (up to nine decimal places).</value>
        [DataMember(Name="createdTime", EmitDefaultValue=false)]
        public string CreatedTime { get; set; }

        /// <summary>
        /// The total profit/loss realized over the lifetime of the Account.
        /// </summary>
        /// <value>The total profit/loss realized over the lifetime of the Account.</value>
        [DataMember(Name="pl", EmitDefaultValue=false)]
        public double Pl { get; set; }

        /// <summary>
        /// The total realized profit/loss for the Account since it was last reset by the client.
        /// </summary>
        /// <value>The total realized profit/loss for the Account since it was last reset by the client.</value>
        [DataMember(Name="resettablePL", EmitDefaultValue=false)]
        public double ResettablePL { get; set; }

        /// <summary>
        /// A date and time value using either RFC3339 or UNIX time representation. The RFC 3339 representation is a string conforming to https://tools.ietf.org/rfc/rfc3339.txt. The Unix representation is a string representing the number of seconds since the Unix Epoch (January 1st, 1970 at UTC). The value is a fractional number, where the fractional part represents a fraction of a second (up to nine decimal places).
        /// </summary>
        /// <value>A date and time value using either RFC3339 or UNIX time representation. The RFC 3339 representation is a string conforming to https://tools.ietf.org/rfc/rfc3339.txt. The Unix representation is a string representing the number of seconds since the Unix Epoch (January 1st, 1970 at UTC). The value is a fractional number, where the fractional part represents a fraction of a second (up to nine decimal places).</value>
        [DataMember(Name="resettablePLTime", EmitDefaultValue=false)]
        public string ResettablePLTime { get; set; }

        /// <summary>
        /// The total amount of financing paid/collected over the lifetime of the Account.
        /// </summary>
        /// <value>The total amount of financing paid/collected over the lifetime of the Account.</value>
        [DataMember(Name="financing", EmitDefaultValue=false)]
        public double Financing { get; set; }

        /// <summary>
        /// The total amount of commission paid over the lifetime of the Account.
        /// </summary>
        /// <value>The total amount of commission paid over the lifetime of the Account.</value>
        [DataMember(Name="commission", EmitDefaultValue=false)]
        public double Commission { get; set; }

        /// <summary>
        /// The total amount of fees charged over the lifetime of the Account for the execution of guaranteed Stop Loss Orders.
        /// </summary>
        /// <value>The total amount of fees charged over the lifetime of the Account for the execution of guaranteed Stop Loss Orders.</value>
        [DataMember(Name="guaranteedExecutionFees", EmitDefaultValue=false)]
        public double GuaranteedExecutionFees { get; set; }

        /// <summary>
        /// Client-provided margin rate override for the Account. The effective margin rate of the Account is the lesser of this value and the OANDA margin rate for the Account&#39;s division. This value is only provided if a margin rate override exists for the Account.
        /// </summary>
        /// <value>Client-provided margin rate override for the Account. The effective margin rate of the Account is the lesser of this value and the OANDA margin rate for the Account&#39;s division. This value is only provided if a margin rate override exists for the Account.</value>
        [DataMember(Name="marginRate", EmitDefaultValue=false)]
        public double MarginRate { get; set; }

        /// <summary>
        /// A date and time value using either RFC3339 or UNIX time representation. The RFC 3339 representation is a string conforming to https://tools.ietf.org/rfc/rfc3339.txt. The Unix representation is a string representing the number of seconds since the Unix Epoch (January 1st, 1970 at UTC). The value is a fractional number, where the fractional part represents a fraction of a second (up to nine decimal places).
        /// </summary>
        /// <value>A date and time value using either RFC3339 or UNIX time representation. The RFC 3339 representation is a string conforming to https://tools.ietf.org/rfc/rfc3339.txt. The Unix representation is a string representing the number of seconds since the Unix Epoch (January 1st, 1970 at UTC). The value is a fractional number, where the fractional part represents a fraction of a second (up to nine decimal places).</value>
        [DataMember(Name="marginCallEnterTime", EmitDefaultValue=false)]
        public string MarginCallEnterTime { get; set; }

        /// <summary>
        /// The number of times that the Account&#39;s current margin call was extended.
        /// </summary>
        /// <value>The number of times that the Account&#39;s current margin call was extended.</value>
        [DataMember(Name="marginCallExtensionCount", EmitDefaultValue=false)]
        public int MarginCallExtensionCount { get; set; }

        /// <summary>
        /// A date and time value using either RFC3339 or UNIX time representation. The RFC 3339 representation is a string conforming to https://tools.ietf.org/rfc/rfc3339.txt. The Unix representation is a string representing the number of seconds since the Unix Epoch (January 1st, 1970 at UTC). The value is a fractional number, where the fractional part represents a fraction of a second (up to nine decimal places).
        /// </summary>
        /// <value>A date and time value using either RFC3339 or UNIX time representation. The RFC 3339 representation is a string conforming to https://tools.ietf.org/rfc/rfc3339.txt. The Unix representation is a string representing the number of seconds since the Unix Epoch (January 1st, 1970 at UTC). The value is a fractional number, where the fractional part represents a fraction of a second (up to nine decimal places).</value>
        [DataMember(Name="lastMarginCallExtensionTime", EmitDefaultValue=false)]
        public string LastMarginCallExtensionTime { get; set; }

        /// <summary>
        /// The number of Trades currently open in the Account.
        /// </summary>
        /// <value>The number of Trades currently open in the Account.</value>
        [DataMember(Name="openTradeCount", EmitDefaultValue=false)]
        public int OpenTradeCount { get; set; }

        /// <summary>
        /// The number of Positions currently open in the Account.
        /// </summary>
        /// <value>The number of Positions currently open in the Account.</value>
        [DataMember(Name="openPositionCount", EmitDefaultValue=false)]
        public int OpenPositionCount { get; set; }

        /// <summary>
        /// The number of Orders currently pending in the Account.
        /// </summary>
        /// <value>The number of Orders currently pending in the Account.</value>
        [DataMember(Name="pendingOrderCount", EmitDefaultValue=false)]
        public int PendingOrderCount { get; set; }

        /// <summary>
        /// Flag indicating that the Account has hedging enabled.
        /// </summary>
        /// <value>Flag indicating that the Account has hedging enabled.</value>
        [DataMember(Name="hedgingEnabled", EmitDefaultValue=false)]
        public bool HedgingEnabled { get; set; }

        /// <summary>
        /// A date and time value using either RFC3339 or UNIX time representation. The RFC 3339 representation is a string conforming to https://tools.ietf.org/rfc/rfc3339.txt. The Unix representation is a string representing the number of seconds since the Unix Epoch (January 1st, 1970 at UTC). The value is a fractional number, where the fractional part represents a fraction of a second (up to nine decimal places).
        /// </summary>
        /// <value>A date and time value using either RFC3339 or UNIX time representation. The RFC 3339 representation is a string conforming to https://tools.ietf.org/rfc/rfc3339.txt. The Unix representation is a string representing the number of seconds since the Unix Epoch (January 1st, 1970 at UTC). The value is a fractional number, where the fractional part represents a fraction of a second (up to nine decimal places).</value>
        [DataMember(Name="lastOrderFillTimestamp", EmitDefaultValue=false)]
        public string LastOrderFillTimestamp { get; set; }

        /// <summary>
        /// The ID of the last Transaction created for the Account.
        /// </summary>
        /// <value>The ID of the last Transaction created for the Account.</value>
        [DataMember(Name="lastTransactionId", EmitDefaultValue=false)]
        public int LastTransactionId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class AccountSummaryAllOf {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Alias: ").Append(Alias).Append("\n");
            sb.Append("  Currency: ").Append(Currency).Append("\n");
            sb.Append("  Balance: ").Append(Balance).Append("\n");
            sb.Append("  CreatedByUserID: ").Append(CreatedByUserID).Append("\n");
            sb.Append("  CreatedTime: ").Append(CreatedTime).Append("\n");
            sb.Append("  GuaranteedStopLossOrderMode: ").Append(GuaranteedStopLossOrderMode).Append("\n");
            sb.Append("  Pl: ").Append(Pl).Append("\n");
            sb.Append("  ResettablePL: ").Append(ResettablePL).Append("\n");
            sb.Append("  ResettablePLTime: ").Append(ResettablePLTime).Append("\n");
            sb.Append("  Financing: ").Append(Financing).Append("\n");
            sb.Append("  Commission: ").Append(Commission).Append("\n");
            sb.Append("  GuaranteedExecutionFees: ").Append(GuaranteedExecutionFees).Append("\n");
            sb.Append("  MarginRate: ").Append(MarginRate).Append("\n");
            sb.Append("  MarginCallEnterTime: ").Append(MarginCallEnterTime).Append("\n");
            sb.Append("  MarginCallExtensionCount: ").Append(MarginCallExtensionCount).Append("\n");
            sb.Append("  LastMarginCallExtensionTime: ").Append(LastMarginCallExtensionTime).Append("\n");
            sb.Append("  OpenTradeCount: ").Append(OpenTradeCount).Append("\n");
            sb.Append("  OpenPositionCount: ").Append(OpenPositionCount).Append("\n");
            sb.Append("  PendingOrderCount: ").Append(PendingOrderCount).Append("\n");
            sb.Append("  HedgingEnabled: ").Append(HedgingEnabled).Append("\n");
            sb.Append("  LastOrderFillTimestamp: ").Append(LastOrderFillTimestamp).Append("\n");
            sb.Append("  LastTransactionId: ").Append(LastTransactionId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as AccountSummaryAllOf);
        }

        /// <summary>
        /// Returns true if AccountSummaryAllOf instances are equal
        /// </summary>
        /// <param name="input">Instance of AccountSummaryAllOf to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(AccountSummaryAllOf input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Id == input.Id ||
                    (this.Id != null &&
                    this.Id.Equals(input.Id))
                ) && 
                (
                    this.Alias == input.Alias ||
                    (this.Alias != null &&
                    this.Alias.Equals(input.Alias))
                ) && 
                (
                    this.Currency == input.Currency ||
                    this.Currency.Equals(input.Currency)
                ) && 
                (
                    this.Balance == input.Balance ||
                    this.Balance.Equals(input.Balance)
                ) && 
                (
                    this.CreatedByUserID == input.CreatedByUserID ||
                    this.CreatedByUserID.Equals(input.CreatedByUserID)
                ) && 
                (
                    this.CreatedTime == input.CreatedTime ||
                    (this.CreatedTime != null &&
                    this.CreatedTime.Equals(input.CreatedTime))
                ) && 
                (
                    this.GuaranteedStopLossOrderMode == input.GuaranteedStopLossOrderMode ||
                    this.GuaranteedStopLossOrderMode.Equals(input.GuaranteedStopLossOrderMode)
                ) && 
                (
                    this.Pl == input.Pl ||
                    this.Pl.Equals(input.Pl)
                ) && 
                (
                    this.ResettablePL == input.ResettablePL ||
                    this.ResettablePL.Equals(input.ResettablePL)
                ) && 
                (
                    this.ResettablePLTime == input.ResettablePLTime ||
                    (this.ResettablePLTime != null &&
                    this.ResettablePLTime.Equals(input.ResettablePLTime))
                ) && 
                (
                    this.Financing == input.Financing ||
                    this.Financing.Equals(input.Financing)
                ) && 
                (
                    this.Commission == input.Commission ||
                    this.Commission.Equals(input.Commission)
                ) && 
                (
                    this.GuaranteedExecutionFees == input.GuaranteedExecutionFees ||
                    this.GuaranteedExecutionFees.Equals(input.GuaranteedExecutionFees)
                ) && 
                (
                    this.MarginRate == input.MarginRate ||
                    this.MarginRate.Equals(input.MarginRate)
                ) && 
                (
                    this.MarginCallEnterTime == input.MarginCallEnterTime ||
                    (this.MarginCallEnterTime != null &&
                    this.MarginCallEnterTime.Equals(input.MarginCallEnterTime))
                ) && 
                (
                    this.MarginCallExtensionCount == input.MarginCallExtensionCount ||
                    this.MarginCallExtensionCount.Equals(input.MarginCallExtensionCount)
                ) && 
                (
                    this.LastMarginCallExtensionTime == input.LastMarginCallExtensionTime ||
                    (this.LastMarginCallExtensionTime != null &&
                    this.LastMarginCallExtensionTime.Equals(input.LastMarginCallExtensionTime))
                ) && 
                (
                    this.OpenTradeCount == input.OpenTradeCount ||
                    this.OpenTradeCount.Equals(input.OpenTradeCount)
                ) && 
                (
                    this.OpenPositionCount == input.OpenPositionCount ||
                    this.OpenPositionCount.Equals(input.OpenPositionCount)
                ) && 
                (
                    this.PendingOrderCount == input.PendingOrderCount ||
                    this.PendingOrderCount.Equals(input.PendingOrderCount)
                ) && 
                (
                    this.HedgingEnabled == input.HedgingEnabled ||
                    this.HedgingEnabled.Equals(input.HedgingEnabled)
                ) && 
                (
                    this.LastOrderFillTimestamp == input.LastOrderFillTimestamp ||
                    (this.LastOrderFillTimestamp != null &&
                    this.LastOrderFillTimestamp.Equals(input.LastOrderFillTimestamp))
                ) && 
                (
                    this.LastTransactionId == input.LastTransactionId ||
                    this.LastTransactionId.Equals(input.LastTransactionId)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Id != null)
                    hashCode = hashCode * 59 + this.Id.GetHashCode();
                if (this.Alias != null)
                    hashCode = hashCode * 59 + this.Alias.GetHashCode();
                hashCode = hashCode * 59 + this.Currency.GetHashCode();
                hashCode = hashCode * 59 + this.Balance.GetHashCode();
                hashCode = hashCode * 59 + this.CreatedByUserID.GetHashCode();
                if (this.CreatedTime != null)
                    hashCode = hashCode * 59 + this.CreatedTime.GetHashCode();
                hashCode = hashCode * 59 + this.GuaranteedStopLossOrderMode.GetHashCode();
                hashCode = hashCode * 59 + this.Pl.GetHashCode();
                hashCode = hashCode * 59 + this.ResettablePL.GetHashCode();
                if (this.ResettablePLTime != null)
                    hashCode = hashCode * 59 + this.ResettablePLTime.GetHashCode();
                hashCode = hashCode * 59 + this.Financing.GetHashCode();
                hashCode = hashCode * 59 + this.Commission.GetHashCode();
                hashCode = hashCode * 59 + this.GuaranteedExecutionFees.GetHashCode();
                hashCode = hashCode * 59 + this.MarginRate.GetHashCode();
                if (this.MarginCallEnterTime != null)
                    hashCode = hashCode * 59 + this.MarginCallEnterTime.GetHashCode();
                hashCode = hashCode * 59 + this.MarginCallExtensionCount.GetHashCode();
                if (this.LastMarginCallExtensionTime != null)
                    hashCode = hashCode * 59 + this.LastMarginCallExtensionTime.GetHashCode();
                hashCode = hashCode * 59 + this.OpenTradeCount.GetHashCode();
                hashCode = hashCode * 59 + this.OpenPositionCount.GetHashCode();
                hashCode = hashCode * 59 + this.PendingOrderCount.GetHashCode();
                hashCode = hashCode * 59 + this.HedgingEnabled.GetHashCode();
                if (this.LastOrderFillTimestamp != null)
                    hashCode = hashCode * 59 + this.LastOrderFillTimestamp.GetHashCode();
                hashCode = hashCode * 59 + this.LastTransactionId.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Id (string) pattern
            Regex regexId = new Regex(@"^\\d+-\\d+-\\d+-\\d+$", RegexOptions.CultureInvariant);
            if (false == regexId.Match(this.Id).Success)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Id, must match a pattern of " + regexId, new [] { "Id" });
            }

            // CreatedTime (string) pattern
            Regex regexCreatedTime = new Regex(@"^(?:(?:\\d+(?:\\.\\d{1,9})?)|(?:[1-9]\\d{3}-(?:(?:0[1-9]|1[0-2])-(?:0[1-9]|1\\d|2[0-8])|(?:0[13-9]|1[0-2])-(?:29|30)|(?:0[13578]|1[02])-31)|(?:[1-9]\\d(?:0[48]|[2468][048]|[13579][26])|(?:[2468][048]|[13579][26])00)-02-29)T(?:[01]\\d|2[0-3]):[0-5]\\d:[0-5]\\d(?:\\.\\d{1,9})?(?:Z|[+-][01]\\d:[0-5]\\d))$", RegexOptions.CultureInvariant);
            if (false == regexCreatedTime.Match(this.CreatedTime).Success)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for CreatedTime, must match a pattern of " + regexCreatedTime, new [] { "CreatedTime" });
            }

            // ResettablePLTime (string) pattern
            Regex regexResettablePLTime = new Regex(@"^(?:(?:\\d+(?:\\.\\d{1,9})?)|(?:[1-9]\\d{3}-(?:(?:0[1-9]|1[0-2])-(?:0[1-9]|1\\d|2[0-8])|(?:0[13-9]|1[0-2])-(?:29|30)|(?:0[13578]|1[02])-31)|(?:[1-9]\\d(?:0[48]|[2468][048]|[13579][26])|(?:[2468][048]|[13579][26])00)-02-29)T(?:[01]\\d|2[0-3]):[0-5]\\d:[0-5]\\d(?:\\.\\d{1,9})?(?:Z|[+-][01]\\d:[0-5]\\d))$", RegexOptions.CultureInvariant);
            if (false == regexResettablePLTime.Match(this.ResettablePLTime).Success)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for ResettablePLTime, must match a pattern of " + regexResettablePLTime, new [] { "ResettablePLTime" });
            }

            // MarginCallEnterTime (string) pattern
            Regex regexMarginCallEnterTime = new Regex(@"^(?:(?:\\d+(?:\\.\\d{1,9})?)|(?:[1-9]\\d{3}-(?:(?:0[1-9]|1[0-2])-(?:0[1-9]|1\\d|2[0-8])|(?:0[13-9]|1[0-2])-(?:29|30)|(?:0[13578]|1[02])-31)|(?:[1-9]\\d(?:0[48]|[2468][048]|[13579][26])|(?:[2468][048]|[13579][26])00)-02-29)T(?:[01]\\d|2[0-3]):[0-5]\\d:[0-5]\\d(?:\\.\\d{1,9})?(?:Z|[+-][01]\\d:[0-5]\\d))$", RegexOptions.CultureInvariant);
            if (false == regexMarginCallEnterTime.Match(this.MarginCallEnterTime).Success)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for MarginCallEnterTime, must match a pattern of " + regexMarginCallEnterTime, new [] { "MarginCallEnterTime" });
            }

            // LastMarginCallExtensionTime (string) pattern
            Regex regexLastMarginCallExtensionTime = new Regex(@"^(?:(?:\\d+(?:\\.\\d{1,9})?)|(?:[1-9]\\d{3}-(?:(?:0[1-9]|1[0-2])-(?:0[1-9]|1\\d|2[0-8])|(?:0[13-9]|1[0-2])-(?:29|30)|(?:0[13578]|1[02])-31)|(?:[1-9]\\d(?:0[48]|[2468][048]|[13579][26])|(?:[2468][048]|[13579][26])00)-02-29)T(?:[01]\\d|2[0-3]):[0-5]\\d:[0-5]\\d(?:\\.\\d{1,9})?(?:Z|[+-][01]\\d:[0-5]\\d))$", RegexOptions.CultureInvariant);
            if (false == regexLastMarginCallExtensionTime.Match(this.LastMarginCallExtensionTime).Success)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for LastMarginCallExtensionTime, must match a pattern of " + regexLastMarginCallExtensionTime, new [] { "LastMarginCallExtensionTime" });
            }

            // LastOrderFillTimestamp (string) pattern
            Regex regexLastOrderFillTimestamp = new Regex(@"^(?:(?:\\d+(?:\\.\\d{1,9})?)|(?:[1-9]\\d{3}-(?:(?:0[1-9]|1[0-2])-(?:0[1-9]|1\\d|2[0-8])|(?:0[13-9]|1[0-2])-(?:29|30)|(?:0[13578]|1[02])-31)|(?:[1-9]\\d(?:0[48]|[2468][048]|[13579][26])|(?:[2468][048]|[13579][26])00)-02-29)T(?:[01]\\d|2[0-3]):[0-5]\\d:[0-5]\\d(?:\\.\\d{1,9})?(?:Z|[+-][01]\\d:[0-5]\\d))$", RegexOptions.CultureInvariant);
            if (false == regexLastOrderFillTimestamp.Match(this.LastOrderFillTimestamp).Success)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for LastOrderFillTimestamp, must match a pattern of " + regexLastOrderFillTimestamp, new [] { "LastOrderFillTimestamp" });
            }

            yield break;
        }
    }

}
