/* 
 * OANDA v20 API
 *
 * The full OANDA v20 API Specification. This specification defines how to interact with v20 Accounts, Trades, Orders, Pricing and more.
 *
 * The version of the OpenAPI document: 3.0.25
 * Contact: api@oanda.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = GeriRemenyi.Oanda.V20.Client.Client.OpenAPIDateConverter;

namespace GeriRemenyi.Oanda.V20.Client.Model
{
    /// <summary>
    /// DependentTradeOrdersBadRequestResponseAllOf
    /// </summary>
    [DataContract]
    public partial class DependentTradeOrdersBadRequestResponseAllOf :  IEquatable<DependentTradeOrdersBadRequestResponseAllOf>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DependentTradeOrdersBadRequestResponseAllOf" /> class.
        /// </summary>
        /// <param name="takeProfitOrderCancelRejectTransaction">takeProfitOrderCancelRejectTransaction.</param>
        /// <param name="takeProfitOrderRejectTransaction">takeProfitOrderRejectTransaction.</param>
        /// <param name="stopLossOrderCancelRejectTransaction">stopLossOrderCancelRejectTransaction.</param>
        /// <param name="stopLossOrderRejectTransaction">stopLossOrderRejectTransaction.</param>
        /// <param name="trailingStopLossOrderCancelRejectTransaction">trailingStopLossOrderCancelRejectTransaction.</param>
        /// <param name="trailingStopLossOrderRejectTransaction">trailingStopLossOrderRejectTransaction.</param>
        public DependentTradeOrdersBadRequestResponseAllOf(OrderCancelRejectTransaction takeProfitOrderCancelRejectTransaction = default(OrderCancelRejectTransaction), TakeProfitOrderRejectTransaction takeProfitOrderRejectTransaction = default(TakeProfitOrderRejectTransaction), OrderCancelRejectTransaction stopLossOrderCancelRejectTransaction = default(OrderCancelRejectTransaction), StopLossOrderRejectTransaction stopLossOrderRejectTransaction = default(StopLossOrderRejectTransaction), OrderCancelRejectTransaction trailingStopLossOrderCancelRejectTransaction = default(OrderCancelRejectTransaction), TrailingStopLossOrderRejectTransaction trailingStopLossOrderRejectTransaction = default(TrailingStopLossOrderRejectTransaction))
        {
            this.TakeProfitOrderCancelRejectTransaction = takeProfitOrderCancelRejectTransaction;
            this.TakeProfitOrderRejectTransaction = takeProfitOrderRejectTransaction;
            this.StopLossOrderCancelRejectTransaction = stopLossOrderCancelRejectTransaction;
            this.StopLossOrderRejectTransaction = stopLossOrderRejectTransaction;
            this.TrailingStopLossOrderCancelRejectTransaction = trailingStopLossOrderCancelRejectTransaction;
            this.TrailingStopLossOrderRejectTransaction = trailingStopLossOrderRejectTransaction;
        }
        
        /// <summary>
        /// Gets or Sets TakeProfitOrderCancelRejectTransaction
        /// </summary>
        [DataMember(Name="takeProfitOrderCancelRejectTransaction", EmitDefaultValue=false)]
        public OrderCancelRejectTransaction TakeProfitOrderCancelRejectTransaction { get; set; }

        /// <summary>
        /// Gets or Sets TakeProfitOrderRejectTransaction
        /// </summary>
        [DataMember(Name="takeProfitOrderRejectTransaction", EmitDefaultValue=false)]
        public TakeProfitOrderRejectTransaction TakeProfitOrderRejectTransaction { get; set; }

        /// <summary>
        /// Gets or Sets StopLossOrderCancelRejectTransaction
        /// </summary>
        [DataMember(Name="stopLossOrderCancelRejectTransaction", EmitDefaultValue=false)]
        public OrderCancelRejectTransaction StopLossOrderCancelRejectTransaction { get; set; }

        /// <summary>
        /// Gets or Sets StopLossOrderRejectTransaction
        /// </summary>
        [DataMember(Name="stopLossOrderRejectTransaction", EmitDefaultValue=false)]
        public StopLossOrderRejectTransaction StopLossOrderRejectTransaction { get; set; }

        /// <summary>
        /// Gets or Sets TrailingStopLossOrderCancelRejectTransaction
        /// </summary>
        [DataMember(Name="trailingStopLossOrderCancelRejectTransaction", EmitDefaultValue=false)]
        public OrderCancelRejectTransaction TrailingStopLossOrderCancelRejectTransaction { get; set; }

        /// <summary>
        /// Gets or Sets TrailingStopLossOrderRejectTransaction
        /// </summary>
        [DataMember(Name="trailingStopLossOrderRejectTransaction", EmitDefaultValue=false)]
        public TrailingStopLossOrderRejectTransaction TrailingStopLossOrderRejectTransaction { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class DependentTradeOrdersBadRequestResponseAllOf {\n");
            sb.Append("  TakeProfitOrderCancelRejectTransaction: ").Append(TakeProfitOrderCancelRejectTransaction).Append("\n");
            sb.Append("  TakeProfitOrderRejectTransaction: ").Append(TakeProfitOrderRejectTransaction).Append("\n");
            sb.Append("  StopLossOrderCancelRejectTransaction: ").Append(StopLossOrderCancelRejectTransaction).Append("\n");
            sb.Append("  StopLossOrderRejectTransaction: ").Append(StopLossOrderRejectTransaction).Append("\n");
            sb.Append("  TrailingStopLossOrderCancelRejectTransaction: ").Append(TrailingStopLossOrderCancelRejectTransaction).Append("\n");
            sb.Append("  TrailingStopLossOrderRejectTransaction: ").Append(TrailingStopLossOrderRejectTransaction).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as DependentTradeOrdersBadRequestResponseAllOf);
        }

        /// <summary>
        /// Returns true if DependentTradeOrdersBadRequestResponseAllOf instances are equal
        /// </summary>
        /// <param name="input">Instance of DependentTradeOrdersBadRequestResponseAllOf to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(DependentTradeOrdersBadRequestResponseAllOf input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.TakeProfitOrderCancelRejectTransaction == input.TakeProfitOrderCancelRejectTransaction ||
                    (this.TakeProfitOrderCancelRejectTransaction != null &&
                    this.TakeProfitOrderCancelRejectTransaction.Equals(input.TakeProfitOrderCancelRejectTransaction))
                ) && 
                (
                    this.TakeProfitOrderRejectTransaction == input.TakeProfitOrderRejectTransaction ||
                    (this.TakeProfitOrderRejectTransaction != null &&
                    this.TakeProfitOrderRejectTransaction.Equals(input.TakeProfitOrderRejectTransaction))
                ) && 
                (
                    this.StopLossOrderCancelRejectTransaction == input.StopLossOrderCancelRejectTransaction ||
                    (this.StopLossOrderCancelRejectTransaction != null &&
                    this.StopLossOrderCancelRejectTransaction.Equals(input.StopLossOrderCancelRejectTransaction))
                ) && 
                (
                    this.StopLossOrderRejectTransaction == input.StopLossOrderRejectTransaction ||
                    (this.StopLossOrderRejectTransaction != null &&
                    this.StopLossOrderRejectTransaction.Equals(input.StopLossOrderRejectTransaction))
                ) && 
                (
                    this.TrailingStopLossOrderCancelRejectTransaction == input.TrailingStopLossOrderCancelRejectTransaction ||
                    (this.TrailingStopLossOrderCancelRejectTransaction != null &&
                    this.TrailingStopLossOrderCancelRejectTransaction.Equals(input.TrailingStopLossOrderCancelRejectTransaction))
                ) && 
                (
                    this.TrailingStopLossOrderRejectTransaction == input.TrailingStopLossOrderRejectTransaction ||
                    (this.TrailingStopLossOrderRejectTransaction != null &&
                    this.TrailingStopLossOrderRejectTransaction.Equals(input.TrailingStopLossOrderRejectTransaction))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.TakeProfitOrderCancelRejectTransaction != null)
                    hashCode = hashCode * 59 + this.TakeProfitOrderCancelRejectTransaction.GetHashCode();
                if (this.TakeProfitOrderRejectTransaction != null)
                    hashCode = hashCode * 59 + this.TakeProfitOrderRejectTransaction.GetHashCode();
                if (this.StopLossOrderCancelRejectTransaction != null)
                    hashCode = hashCode * 59 + this.StopLossOrderCancelRejectTransaction.GetHashCode();
                if (this.StopLossOrderRejectTransaction != null)
                    hashCode = hashCode * 59 + this.StopLossOrderRejectTransaction.GetHashCode();
                if (this.TrailingStopLossOrderCancelRejectTransaction != null)
                    hashCode = hashCode * 59 + this.TrailingStopLossOrderCancelRejectTransaction.GetHashCode();
                if (this.TrailingStopLossOrderRejectTransaction != null)
                    hashCode = hashCode * 59 + this.TrailingStopLossOrderRejectTransaction.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
